services:
  db:
    image: postgres:17-alpine
    container_name: cnp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cnp_net

  backend:
    image: matix22/cnp_api:latest
    container_name: cnp_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      FRONT_PORT: ${FRONT_PORT}
      API_PORT: ${FASTIFY_PORT}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      FASTIFY_SECRET: ${FASTIFY_SECRET}
    depends_on:
      - postgres
    networks:
      - cnp_net

  frontend:
    image: matix22/cnp_frontend:latest
    container_name: cnp_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - cnp_net

  nginx:
    image: nginx:1.27-alpine
    container_name: cnp_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - cnp_net

  certbot:
    image: certbot/certbot:latest
    container_name: cnp_certbot
    command: >
      certbot certonly --webroot
      -w /var/www/certbot
      --agree-tos
      --register-unsafely-without-email
      -d grupo01.brazilsouth.cloudapp.azure.com
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - cnp_net

volumes:
  cnp_postgres_data:

networks:
  cnp_net:
    driver: bridge
